---
title: "Growth, Survival, Diversity and Concentration"
author:
  - name: "Eric Marcon"
  - name: "Florence Puech"
abstract: >
  Exploratory model of growth and survival depending on Diversity and concentration.
date: "`r format(Sys.time(), '%d %B %Y')`"
url: https://EricMarcon.github.io/Growth-Survival-Diversity/
github-repo: EricMarcon/Growth-Survival-Diversity
# Language
lang: en-US
# Bibliography
bibliography: references.bib
biblio-style: chicago
# LaTeX
# Print table of contents in PDFs?
pdftoc: false
# If true, choose its depth
toc-depth: 3
# URL color
urlcolor: blue
# Do not modify
always_allow_html: yes
csquotes: true
output:
  rmdformats::downcute:
    use_bookdown: yes
    lightbox: yes
  bookdown::pdf_book:
    template: latex/template.tex
    citation_package: natbib
    latex_engine: xelatex
    keep_tex: yes
---

```{r DoNotModify, include=FALSE}
### Utilities. Do not modify.
# Installation of packages if necessary
InstallPackages <- function(Packages) {
  InstallPackage <- function(Package) {
    if (!Package %in% installed.packages()[, 1]) {
      install.packages(Package, repos="https://cran.rstudio.com/")
    }
  }
  invisible(sapply(Packages, InstallPackage))
}

# Basic packages
InstallPackages(c("bookdown", "formatR", "kableExtra", "ragg"))

# kableExtra must be loaded 
if (knitr::opts_knit$get("rmarkdown.pandoc.to") == "docx") {
  # Word output (https://stackoverflow.com/questions/35144130/in-knitr-how-can-i-test-for-if-the-output-will-be-pdf-or-word)
  # Do not use autoformat (https://github.com/haozhu233/kableExtra/issues/308)
  options(kableExtra.auto_format = FALSE)
}
library("kableExtra")

# Chunk font size hook: allows size='small' or any valid Latex font size in chunk options
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\n \\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
```

```{r Options, include=FALSE}
### Customized options for this document
# Add necessary packages here
Packages <- c("tidyverse", "remotes", "spatstat", "dbmss")
# Install them
InstallPackages(Packages)
# From GitHub
remotes::install_github("EricMarcon/SpatDiv")

# knitr options
knitr::opts_chunk$set(
  cache =   FALSE,    # Cache chunk results
  include = TRUE,     # Show/Hide chunks
  echo =    TRUE,     # Show/Hide code
  warning = FALSE,    # Show/Hide warnings
  message = FALSE,    # Show/Hide messages
  # Figure alignment and size
  fig.align = 'center', out.width = '80%',
  # Graphic devices (ragg_png is better than standard png)
  dev = c("ragg_png", "pdf"),
  # Code chunk format
  tidy = TRUE, tidy.opts = list(blank=FALSE, width.cutoff=50),
  size = "scriptsize", knitr.graphics.auto_pdf = TRUE
  )
options(width = 50)

# ggplot style
library("tidyverse")
theme_set(theme_bw())
theme_update(panel.background=element_rect(fill="transparent", colour=NA),
             plot.background=element_rect(fill="transparent", colour=NA))
knitr::opts_chunk$set(dev.args=list(bg="transparent"))

# Random seed
set.seed(973)
```


# Data generation

## Point set

Plants are simulated in a square window 

```{r}
library("SpatDiv")
# Geometry of the window
window_size <- 20000
unit_name <- c("meter", "meters")
# Density
plants_n_per_area <- 100/1E6
# Number of sectors
sectors_n <- 20
# Spatial concentration of plants
thomas_scale <- window_size/10
thomas_mu <- 100
```

The community is simulated:

```{r}
library("spatstat")
rSpCommunity(
  n = 1, 
  size = window_size^2 * plants_n_per_area, 
  S = sectors_n, 
  Spatial = "Thomas", scale = thomas_scale, mu = thomas_mu,
  Sizes = "Weibull",
  win = square(r = window_size, unitname = unit_name)
) -> spCommunity
# Number of plants
spCommunity$n
# Per sector
summary(spCommunity$marks$PointType)
# Sizes
hist(spCommunity$marks$PointWeight)
```

## Parameters

```{r}
n_simulations <- 10
```


# Diversity

Accumulation.

```{r}
# Average distance between plants
dist_neighbor <- 1 / sqrt(plants_n_per_area)
# Accumulation of diversity with confidence interval (not run)
# accum <- DivAccum(
#   spCommunity, 
#   r.seq = c(
#     0, 
#     seq(
#       from = dist_neighbor / 4, 
#       to = dist_neighbor * 4, 
#       by = dist_neighbor / 4
#     )
#   ),
#   q.seq = 0:2, 
#   H0 = "RandomLocation", 
#   NumberOfSimulations = n_simulations,
#   Individual = TRUE
# )
# Diversity at 4 times the average distance to neighbor 
accum_5 <- DivAccum(
  spCommunity, 
  r.seq = c(0, dist_neighbor * 4),
  q.seq = 0:2, 
  Individual = TRUE
)
div_plants <- accum_5$Neighborhoods[1, 2, ]
# Distribution of richness
hist(div_plants)
```

# Concentration

Spatial concentration of sectors

```{r}
# Compute individual M
library("dbmss")
# Compute concentration of each sector
M_plants <- numeric(spCommunity$n)
for (sector in levels(spCommunity$marks$PointType)) {
  M_sector <- Mhat(
    spCommunity, 
    r = c(0, window_size /10),
    ReferenceType = sector, 
    Individual = TRUE
  )
  point_numbers <- as.integer(substring(names(M_sector)[-(1:3)], 3))
  M_plants[point_numbers] <- as.numeric(as.data.frame(M_sector)[2, -(1:3)])
}
hist(m_plants)
```



`r if (!knitr:::is_latex_output()) '# References {-}'`
